AWSTemplateFormatVersion: 2010-09-09
Description: >-
  expedition-api

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 180
    MemorySize: 128
    Architectures:
      - x86_64
    Environment:
      Variables:
        DATABASE_HOST: DATABASE_HOST,
        DATABASE_USER: DATABASE_USER,
        DATABASE_PASSWORD: DATABASE_PASSWORD,
        DATABASE_NAME: DATABASE_NAME

Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Description: A simple example includes a HTTP get method to get all items from a MySQL table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Policies:
        - AmazonRDSFullAccess

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        Target: "es2020"
        Sourcemap: true
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - src/handlers/get-all-items.ts
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);


Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
