AWSTemplateFormatVersion: 2010-09-09
Description: >-
  expedition-api

Transform:
- AWS::Serverless-2016-10-31

Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a MySQL table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Policies:
        - AmazonRDSFullAccess

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        Target: "es2020"
        Sourcemap: true
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - src/handlers/get-all-items.ts
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);


Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
