AWSTemplateFormatVersion: 2010-09-09
Description: >-
  expedition-api

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 180
    MemorySize: 512
    Architectures:
      - x86_64
    Environment:
      Variables:
        DATABASE_HOST: DATABASE_HOST,
        DATABASE_USER: DATABASE_USER,
        DATABASE_PASSWORD: DATABASE_PASSWORD,
        DATABASE_NAME: DATABASE_NAME,
        DATABASE_PORT: DATABASE_PORT

Resources:
  createParticipantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-participant.createParticipant
      Description: A simple example includes a HTTP get method to get all items from a MySQL table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /participants/
            Method: POST
      Policies:
        - AmazonRDSFullAccess

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/create-participant.ts

  submitScores:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/submit-scores.submitScores
      Description: A simple example includes a HTTP get method to get all items from a MySQL table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /scores
            Method: POST
      Policies:
        - AmazonRDSFullAccess

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/submit-scores.ts

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
