AWSTemplateFormatVersion: 2010-09-09
Description: >-
  expedition-api

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  DatabaseHost:
    Type: String
    Description: Database host
  DatabaseUser:
    Type: String
    Description: Database user
  DatabasePassword:
    Type: String
    Description: Database password
  DatabaseName:
    Type: String
    Description: Database name
  DatabasePort:
    Type: Number
    Description: Database port

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 180
    MemorySize: 512
    Architectures:
      - x86_64
    Environment:
      Variables:
        DATABASE_HOST: !Ref DatabaseHost
        DATABASE_USER: !Ref DatabaseUser
        DATABASE_PASSWORD: !Ref DatabasePassword
        DATABASE_NAME: !Ref DatabaseName
        DATABASE_PORT: !Ref DatabasePort

Resources:
  createParticipantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-participant.createParticipant
      Description: Function that creates new participant
      Events:
        Api:
          Type: Api
          Properties:
            Path: /participants/
            Method: POST
      Policies:
        - AmazonRDSFullAccess
        - AmazonVPCCrossAccountNetworkInterfaceOperations
      VpcConfig:
        SecurityGroupIds:
          - sg-0f3bfcf9a0fd05414
        SubnetIds:
          - subnet-083ba1b213db6d7f1
          - subnet-0929d0234f9c7b45e
          - subnet-0c87d47750dc866aa

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/create-participant.ts

  createTeamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-team.createTeam
      Description: Function that creates new team
      Events:
        Api:
          Type: Api
          Properties:
            Path: /teams/
            Method: POST
      Policies:
        - AmazonRDSFullAccess
        - AmazonVPCCrossAccountNetworkInterfaceOperations
      VpcConfig:
        SecurityGroupIds:
          - sg-0f3bfcf9a0fd05414
        SubnetIds:
          - subnet-083ba1b213db6d7f1
          - subnet-0929d0234f9c7b45e
          - subnet-0c87d47750dc866aa

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/create-team.ts

  createUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-user.createUser
      Description: Function that creates new user
      Events:
        Api:
          Type: Api
          Properties:
            Path: /users/
            Method: POST
      Policies:
        - AmazonRDSFullAccess
        - AmazonVPCCrossAccountNetworkInterfaceOperations
      VpcConfig:
        SecurityGroupIds:
          - sg-0f3bfcf9a0fd05414
        SubnetIds:
          - subnet-083ba1b213db6d7f1
          - subnet-0929d0234f9c7b45e
          - subnet-0c87d47750dc866aa

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/create-user.ts

  createActivitiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-activities.createActivities
      Description: Function that creates new activities
      Events:
        Api:
          Type: Api
          Properties:
            Path: /activities/
            Method: POST
      Policies:
        - AmazonRDSFullAccess
        - AmazonVPCCrossAccountNetworkInterfaceOperations
      VpcConfig:
        SecurityGroupIds:
          - sg-0f3bfcf9a0fd05414
        SubnetIds:
          - subnet-083ba1b213db6d7f1
          - subnet-0929d0234f9c7b45e
          - subnet-0c87d47750dc866aa

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/create-activities.ts

  submitScoresFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/submit-scores.submitScores
      Description: Function that submits scores
      Events:
        Api:
          Type: Api
          Properties:
            Path: /scores/
            Method: POST
      Policies:
        - AmazonRDSFullAccess
        - AmazonVPCCrossAccountNetworkInterfaceOperations
      VpcConfig:
        SecurityGroupIds:
          - sg-0f3bfcf9a0fd05414
        SubnetIds:
          - subnet-083ba1b213db6d7f1
          - subnet-0929d0234f9c7b45e
          - subnet-0c87d47750dc866aa

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/submit-scores.ts

  getMyActivitiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-activities.getActivities
      Description: Function that gets my activities
      Events:
        Api:
          Type: Api
          Properties:
            Path: /activities/
            Method: GET
      Policies:
        - AmazonRDSFullAccess
        - AmazonVPCCrossAccountNetworkInterfaceOperations
      VpcConfig:
        SecurityGroupIds:
          - sg-0f3bfcf9a0fd05414
        SubnetIds:
          - subnet-083ba1b213db6d7f1
          - subnet-0929d0234f9c7b45e
          - subnet-0c87d47750dc866aa

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/get-activities.ts

  getUnevalueatedParticipants:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-unevaluated-participants.getUnevaluatedParticipants
      Description: Function that gets unevaluated participants
      Events:
        Api:
          Type: Api
          Properties:
            Path: /participants
            Method: GET
      Policies:
        - AmazonRDSFullAccess
        - AmazonVPCCrossAccountNetworkInterfaceOperations
      VpcConfig:
        SecurityGroupIds:
          - sg-0f3bfcf9a0fd05414
        SubnetIds:
          - subnet-083ba1b213db6d7f1
          - subnet-0929d0234f9c7b45e
          - subnet-0c87d47750dc866aa

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/get-unevaluated-participants.ts

  initializeRelations:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/initialize-relations.initializeRelations
      Description: Function that initializes relations
      Events:
        Api:
          Type: Api
          Properties:
            Path: /relations
            Method: POST
      Policies:
        - AmazonRDSFullAccess
        - AmazonVPCCrossAccountNetworkInterfaceOperations
      VpcConfig:
        SecurityGroupIds:
          - sg-0f3bfcf9a0fd05414
        SubnetIds:
          - subnet-083ba1b213db6d7f1
          - subnet-0929d0234f9c7b45e
          - subnet-0c87d47750dc866aa

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/initialize-relations.ts

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
